# GitHub Pages Configuration
title: MUDEK Ders Değerlendirme Sistemi
description: Mühendislik Eğitim Programları İçin MUDEK Akreditasyon ve Ders Değerlendirme Sistemi
encoding: UTF-8

# GitHub Pages settings
baseurl: ""
url: ""