// Auto-generated version info - DO NOT EDIT
// Generated by MUDEK Hybrid Build System
// Build Mode: production
// Generated: 2025-10-07T01:07:58.403Z

const APP_VERSION_INFO = {
  version: '2.0.0',
  tag: 'v2.0.0-local',
  buildTime: '2025-10-07 01:07:51 UTC',
  buildNumber: 'LOCAL-1759799271421',
  gitSha: 'local-development',
  branch: 'local',
  buildMode: 'production',
  env: 'production'
};

// Export for debugging
if (typeof window !== 'undefined') {
  window.APP_VERSION_INFO = APP_VERSION_INFO;
  console.log('📝 Version-info.js loaded [production]');
}
